### PR TITLE
Fix dependencies and duplicated makedepends

### PR DESCRIPTION
**Pull request by cip91sk**

### CODE REVIEW

**Comment by kamazee** [comment]
Pushed into AUR. Thanks!

**Comment by kamazee** [comment]
@cip91sk oh, by the way, does python-pip have to be in `depends` rather than `makedepends`? I think it's needed only to pull the dependecies which should happen at build time (given that all the dependencies are downloaded). Am I missing anything?

**Comment by kamazee** [comment]
I moved it into `makedepends` and tested it all on a clean arch.
Will move it back, though, if it's needed in `depends`.

**Comment by cip91sk** [comment]
Well to be honest I tried with the package "pip" (in aur) in makedepends
and than just python-pip in depends, so I don't think that you'll have to
move it back if everything works. Thanks for noticing and for the quick
update!
Il 14 mar 2016 09:02, "Alexander Kurilo" notifications@github.com ha
scritto:

**Pull request merged**
